name: Pull Request Workflow

on: push
jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          #      - name: ktlint check
          #        uses: gradle/gradle-build-action@v2
          #        with:
          #          arguments: ktlintCheck
      - name: Run Detekt
        run: ./gradlew detekt

